ALTER TABLE "seal_usage_log"
ADD COLUMN IF NOT EXISTS "page_index" INTEGER,
ADD COLUMN IF NOT EXISTS "x_ratio" DECIMAL(8, 6),
ADD COLUMN IF NOT EXISTS "y_ratio" DECIMAL(8, 6),
ADD COLUMN IF NOT EXISTS "width_ratio" DECIMAL(8, 6);
