import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { CreatePartRequest } from '@erp/shared-types';

@Injectable()
export class PartsService {
  constructor(private readonly prisma: PrismaService) {}
  /**
   * 创建零件
   * @params payload
   * @return Part
   * @Qingsds
   */
  async create(payload: CreatePartRequest) {
    // 1. 自动生成零件编号：规则为 PN-年月日-毫秒时间戳
    // 例如：PN-20260312-171023945
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
    const msStr = now.getTime().toString().slice(-6);
    const autoGeneratedPartNumber = `PN-${dateStr}-${msStr}`;

    const newPart = await this.prisma.client.part.create({
      data: {
        partNumber: autoGeneratedPartNumber,
        name: payload.name,
        material: payload.material,
        commonPrices: payload.commonPrices,
      },
    });

    return newPart;
  }
}
