import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import {
  CreatePartRequest,
  FileType,
  UpdatePartRequest,
  UserRoleType,
} from '@erp/shared-types';
import { Prisma } from '@erp/database';
import { randomUUID } from 'node:crypto';
import { extname } from 'node:path';
import { Readable } from 'node:stream';
import { StorageService } from '../storage/storage.service';

const MAX_DRAWING_SIZE_BYTES = 10 * 1024 * 1024;

function resolveDrawingFileType(file: Express.Multer.File): FileType {
  if (file.mimetype.startsWith('image/')) {
    return FileType.IMAGE;
  }
  if (file.mimetype === 'application/pdf') {
    return FileType.PDF;
  }
  throw new BadRequestException('仅支持上传图片或 PDF 图纸');
}

function resolveFileExtension(file: Express.Multer.File) {
  const originalExt = extname(file.originalname).toLowerCase();
  if (originalExt) {
    return originalExt;
  }
  return file.mimetype === 'application/pdf' ? '.pdf' : '.bin';
}

@Injectable()
export class PartsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly storage: StorageService,
  ) {}

  private sanitizePartForUser<T extends { commonPrices: unknown }>(part: T) {
    return {
      ...part,
      commonPrices: {},
    };
  }

  private normalizeCustomerIds(customerIds?: number[]) {
    if (!Array.isArray(customerIds)) {
      return undefined;
    }

    return [...new Set(customerIds.map(id => Number(id)).filter(id => Number.isInteger(id) && id > 0))];
  }

  private async ensureCustomersExist(
    tx: Prisma.TransactionClient | PrismaService['client'],
    customerIds: number[],
  ) {
    if (customerIds.length === 0) {
      return;
    }

    const customers = await tx.customer.findMany({
      where: { id: { in: customerIds } },
      select: { id: true },
    });

    if (customers.length !== customerIds.length) {
      throw new BadRequestException('部分关联客户不存在，请刷新后重试');
    }
  }

  private async syncPartCustomers(
    tx: Prisma.TransactionClient,
    partId: number,
    customerIds: number[],
  ) {
    await tx.customerPart.deleteMany({ where: { partId } });

    if (customerIds.length === 0) {
      return;
    }

    await tx.customerPart.createMany({
      data: customerIds.map(customerId => ({
        customerId,
        partId,
      })),
      skipDuplicates: true,
    });
  }

  private formatPartRecord<
    T extends {
      customers?: Array<{
        customer: {
          id: number;
          name: string;
          isActive: boolean;
        };
      }>;
    },
  >(part: T) {
    const { customers = [], ...rest } = part;

    return {
      ...rest,
      customers: customers.map(item => item.customer),
    };
  }
  /**
   * 创建零件
   * @params payload
   * @return Part
   * @Qingsds
   */
  async create(payload: CreatePartRequest) {
    // 1. 自动生成零件编号：规则为 PN-年月日-毫秒时间戳
    // 例如：PN-20260312-171023945
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
    const msStr = now.getTime().toString().slice(-6);
    const autoGeneratedPartNumber = `PN-${dateStr}-${msStr}`;

    const customerIds = this.normalizeCustomerIds(payload.customerIds) ?? [];

    return await this.prisma.client.$transaction(async tx => {
      await this.ensureCustomersExist(tx, customerIds);

      const newPart = await tx.part.create({
        data: {
          partNumber: autoGeneratedPartNumber,
          name: payload.name,
          material: payload.material,
          commonPrices: payload.commonPrices,
          spec: payload.spec,
        },
      });

      await this.syncPartCustomers(tx, newPart.id, customerIds);

      const part = await tx.part.findUnique({
        where: { id: newPart.id },
        include: {
          customers: {
            include: {
              customer: {
                select: {
                  id: true,
                  name: true,
                  isActive: true,
                },
              },
            },
          },
        },
      });

      if (!part) {
        throw new NotFoundException(`零件 ID: ${newPart.id} 不存在`);
      }

      return this.formatPartRecord(part);
    });
  }

  // 分页与模糊查询
  async findAll(
    page: number = 1,
    pageSize: number = 1,
    keyword?: string,
    role: UserRoleType = 'ADMIN',
  ) {
    const skip = (page - 1) * pageSize;

    // 构建查询条件：支持按零件号或名称进行模糊匹配
    const where = keyword
      ? {
          OR: [
            { partNumber: { contains: keyword, mode: 'insensitive' as const } },
            { name: { contains: keyword, mode: 'insensitive' as const } },
          ],
        }
      : {};

    const [total, data] = await Promise.all([
      this.prisma.client.part.count({ where }),
      this.prisma.client.part.findMany({
        where,
        skip,
        take: Number(pageSize),
        orderBy: { createdAt: 'desc' }, // 按创建时间倒序
        include: {
          customers: {
            include: {
              customer: {
                select: {
                  id: true,
                  name: true,
                  isActive: true,
                },
              },
            },
          },
        },
      }),
    ]);

    const formatted = data.map(part => this.formatPartRecord(part));

    return {
      total,
      data:
        role === 'ADMIN'
          ? formatted
          : formatted.map(part => this.sanitizePartForUser(part)),
      page: Number(page),
      pageSize: Number(pageSize),
    };
  }

  // 3. 查询单条详情及图纸
  async findOne(id: number, role: UserRoleType = 'ADMIN') {
    const part = await this.prisma.client.part.findUnique({
      where: { id },
      include: {
        drawings: true,
        customers: {
          include: {
            customer: {
              select: {
                id: true,
                name: true,
                isActive: true,
              },
            },
          },
        },
      }, // 联表查出关联的图纸数据
    });

    if (!part) {
      throw new NotFoundException(`零件 ID: ${id} 不存在`);
    }

    const formatted = this.formatPartRecord(part);
    return role === 'ADMIN' ? formatted : this.sanitizePartForUser(formatted);
  }

  // 4. 修改零件信息
  async updatePart(id: number, payload: UpdatePartRequest) {
    const customerIds = this.normalizeCustomerIds(payload.customerIds);

    return await this.prisma.client.$transaction(async tx => {
      const current = await tx.part.findUnique({
        where: { id },
        select: { id: true },
      });

      if (!current) {
        throw new NotFoundException(`零件 ID: ${id} 不存在`);
      }

      if (customerIds) {
        await this.ensureCustomersExist(tx, customerIds);
      }

      await tx.part.update({
        where: { id },
        data: {
          name: payload.name,
          material: payload.material,
          spec: payload.spec,
          commonPrices: payload.commonPrices,
        },
      });

      if (customerIds) {
        await this.syncPartCustomers(tx, id, customerIds);
      }

      const part = await tx.part.findUnique({
        where: { id },
        include: {
          drawings: true,
          customers: {
            include: {
              customer: {
                select: {
                  id: true,
                  name: true,
                  isActive: true,
                },
              },
            },
          },
        },
      });

      if (!part) {
        throw new NotFoundException(`零件 ID: ${id} 不存在`);
      }

      return this.formatPartRecord(part);
    });
  }

  // 5. 删除零件（防止误删已参与订单的主数据）
  async deletePart(id: number) {
    const part = await this.prisma.client.part.findUnique({
      where: { id },
      select: {
        id: true,
        name: true,
        _count: { select: { orderItems: true } },
      },
    });

    if (!part) {
      throw new NotFoundException(`零件 ID: ${id} 不存在`);
    }

    if (part._count.orderItems > 0) {
      throw new BadRequestException(
        `零件「${part.name}」已被订单引用，不能删除`,
      );
    }

    await this.prisma.client.$transaction(async (tx) => {
      await tx.partDrawing.deleteMany({
        where: { partId: id },
      });
      await tx.part.delete({
        where: { id },
      });
    });

    return { id };
  }

  /**
   * 上传零件工程图纸
   */
  async uploadDrawing(partId: number, file: Express.Multer.File) {
    // 1. 校验零件是否存在
    await this.findOne(partId);

    if (!file) {
      throw new BadRequestException('未检测到上传的文件');
    }

    if (!file.buffer?.length) {
      throw new BadRequestException('上传文件内容为空');
    }

    if (file.size > MAX_DRAWING_SIZE_BYTES) {
      throw new BadRequestException('图纸文件不能超过 10MB');
    }

    const fileType = resolveDrawingFileType(file);
    const fileKey = `drawings/part-${partId}/${Date.now()}-${randomUUID()}${resolveFileExtension(file)}`;

    await this.storage.uploadObject({
      key: fileKey,
      body: file.buffer,
      size: file.size,
      contentType: file.mimetype,
    });

    // 3. 开启事务：处理图纸版本更迭
    return await this.prisma.client.$transaction(async (tx) => {
      const newDrawing = await tx.partDrawing.create({
        data: {
          partId: partId,
          fileName: file.originalname,
          fileKey: fileKey,
          fileType: fileType,
          isLatest: true,
        },
      });

      await tx.partDrawing.updateMany({
        where: {
          partId: partId,
          id: { not: newDrawing.id },
        },
        data: { isLatest: false },
      });

      return newDrawing;
    });
  }

  async getDrawingFile(
    partId: number,
    drawingId: number,
  ): Promise<{
    drawing: {
      id: number;
      partId: number;
      fileName: string;
      fileKey: string;
      fileType: string;
    };
    stream: Readable;
    size: number;
    contentType: string;
  }> {
    const drawing = await this.prisma.client.partDrawing.findFirst({
      where: {
        id: drawingId,
        partId,
      },
    });

    if (!drawing) {
      throw new NotFoundException('图纸不存在或不属于当前零件');
    }

    const [stream, stat] = await Promise.all([
      this.storage.getObjectStream(drawing.fileKey),
      this.storage.statObject(drawing.fileKey),
    ]);
    const drawingFileType = drawing.fileType as FileType;
    const metaData = stat.metaData as
      | Record<string, string | undefined>
      | undefined;
    const rawContentType = metaData?.['content-type'];
    const contentType =
      typeof rawContentType === 'string'
        ? rawContentType
        : drawingFileType === FileType.PDF
          ? 'application/pdf'
          : 'application/octet-stream';

    return {
      drawing,
      stream,
      size: stat.size,
      contentType,
    };
  }

  // apps/backend/src/parts/parts.service.ts
  // ... 保持原有 imports 不变

  /**
   * 批量创建零件 (供 Excel 导入使用)
   * @params parts
   * @return { count: number }
   */
  async createBatch(parts: CreatePartRequest[]) {
    if (!parts || parts.length === 0) {
      throw new BadRequestException('导入数据不能为空');
    }

    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
    const baseMs = now.getTime();

    // 预处理数据，为每一行生成唯一的 partNumber
    const dataToInsert = parts.map((part, index) => {
      // 加上 index 偏移量，防止同一毫秒内生成的编号重复
      const msStr = (baseMs + index).toString().slice(-6);
      const autoGeneratedPartNumber = `PN-${dateStr}-${msStr}-${index}`;

      return {
        partNumber: autoGeneratedPartNumber,
        name: part.name,
        material: part.material,
        spec: part.spec,
        // Prisma schema 中定义为 Json 类型，直接传入对象即可
        commonPrices: part.commonPrices || {},
      };
    });

    // 使用 Prisma 的 createMany 进行高性能批量插入
    const result = await this.prisma.client.part.createMany({
      data: dataToInsert,
      skipDuplicates: true, // 忽略可能的重复项，防止整个事务失败
    });

    return result;
  }
}
