/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SealsRouteImport } from './routes/seals'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as DeliveriesIdRouteImport } from './routes/deliveries.$id'
import { Route as BillingNewRouteImport } from './routes/billing.new'
import { Route as BillingIdRouteImport } from './routes/billing.$id'
import { Route as SealsIdLogsRouteImport } from './routes/seals.$id.logs'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SealsRoute = SealsRouteImport.update({
  id: '/seals',
  path: '/seals',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartsRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const DeliveriesIdRoute = DeliveriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeliveriesRoute,
} as any)
const BillingNewRoute = BillingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BillingRoute,
} as any)
const BillingIdRoute = BillingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BillingRoute,
} as any)
const SealsIdLogsRoute = SealsIdLogsRouteImport.update({
  id: '/$id/logs',
  path: '/$id/logs',
  getParentRoute: () => SealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/parts': typeof PartsRouteWithChildren
  '/seals': typeof SealsRouteWithChildren
  '/users': typeof UsersRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/parts/$id': typeof PartsIdRoute
  '/seals/$id/logs': typeof SealsIdLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/parts': typeof PartsRouteWithChildren
  '/seals': typeof SealsRouteWithChildren
  '/users': typeof UsersRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/parts/$id': typeof PartsIdRoute
  '/seals/$id/logs': typeof SealsIdLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/parts': typeof PartsRouteWithChildren
  '/seals': typeof SealsRouteWithChildren
  '/users': typeof UsersRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/parts/$id': typeof PartsIdRoute
  '/seals/$id/logs': typeof SealsIdLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/deliveries'
    | '/login'
    | '/orders'
    | '/parts'
    | '/seals'
    | '/users'
    | '/billing/$id'
    | '/billing/new'
    | '/deliveries/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/parts/$id'
    | '/seals/$id/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/deliveries'
    | '/login'
    | '/orders'
    | '/parts'
    | '/seals'
    | '/users'
    | '/billing/$id'
    | '/billing/new'
    | '/deliveries/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/parts/$id'
    | '/seals/$id/logs'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/deliveries'
    | '/login'
    | '/orders'
    | '/parts'
    | '/seals'
    | '/users'
    | '/billing/$id'
    | '/billing/new'
    | '/deliveries/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/parts/$id'
    | '/seals/$id/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PartsRoute: typeof PartsRouteWithChildren
  SealsRoute: typeof SealsRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seals': {
      id: '/seals'
      path: '/seals'
      fullPath: '/seals'
      preLoaderRoute: typeof SealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof PartsRoute
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/deliveries/$id': {
      id: '/deliveries/$id'
      path: '/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof DeliveriesIdRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/billing/new': {
      id: '/billing/new'
      path: '/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof BillingNewRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/$id': {
      id: '/billing/$id'
      path: '/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof BillingIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/seals/$id/logs': {
      id: '/seals/$id/logs'
      path: '/$id/logs'
      fullPath: '/seals/$id/logs'
      preLoaderRoute: typeof SealsIdLogsRouteImport
      parentRoute: typeof SealsRoute
    }
  }
}

interface BillingRouteChildren {
  BillingIdRoute: typeof BillingIdRoute
  BillingNewRoute: typeof BillingNewRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingIdRoute: BillingIdRoute,
  BillingNewRoute: BillingNewRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface DeliveriesRouteChildren {
  DeliveriesIdRoute: typeof DeliveriesIdRoute
}

const DeliveriesRouteChildren: DeliveriesRouteChildren = {
  DeliveriesIdRoute: DeliveriesIdRoute,
}

const DeliveriesRouteWithChildren = DeliveriesRoute._addFileChildren(
  DeliveriesRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PartsRouteChildren {
  PartsIdRoute: typeof PartsIdRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsIdRoute: PartsIdRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

interface SealsRouteChildren {
  SealsIdLogsRoute: typeof SealsIdLogsRoute
}

const SealsRouteChildren: SealsRouteChildren = {
  SealsIdLogsRoute: SealsIdLogsRoute,
}

const SealsRouteWithChildren = SealsRoute._addFileChildren(SealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRouteWithChildren,
  DeliveriesRoute: DeliveriesRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PartsRoute: PartsRouteWithChildren,
  SealsRoute: SealsRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
